version: "3"

services:
    laravel_eleven_app:
        build:
            args:
                user: laravel_eleven_user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel_eleven_image
        container_name: laravel_eleven_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel_eleven_app_network

    laravel_eleven_webserver:
        image: nginx:alpine
        container_name: laravel_eleven_webserver_container
        restart: unless-stopped
        ports:
            - "6162:80"
        volumes:
            - ./:/var/www/
            - ./docker-compose/nginx/:/etc/nginx/conf.d
        networks:
            - laravel_eleven_app_network

networks:
    laravel_eleven_app_network:
        driver: bridge
